name: "Ampersand amp file deploy action"
description: "A GitHub Action to deploy amp integration"
author: "Ampersand"

inputs:
  api_key:
    description: "Ampersand API key"
    required: true
  project_id:
    description: "Ampersand project id"
    required: true
  directory_path:
    description: "Specify the path to the directory containing the amp file. If not provided, the root directory will be used by default."
    required: true
    default: "."

outputs:
  deployment_status:
    description: "Status of the deployment"


runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.api_key }}
    - ${{ inputs.project_id }}
    - ${{ inputs.directory_path }}