name: "Official Ampersand Github Action"
description: "A GitHub Action to deploy Ampersand integrations"
author: "Ampersand Team"

inputs:
  api_key:
    description: "Ampersand API key"
    required: true
  project_id:
    description: "Ampersand project ID or name"
    required: true
  directory_path:
    description: "Specify the path to the directory containing the amp.yaml file. If not provided, the root directory will be used by default."
    required: false
    default: "."

outputs:
  deployment_status:
    description: "Status of the deployment"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.api_key }}
    - ${{ inputs.project_id }}
    - ${{ inputs.directory_path }}
